### ISSUE TITLE
NetworkResponseExtensions improvements

### ISSUE THREAD

**Issue by eric-taix** [rishad13/dio_with_extension#1]
- NetworkResponseExtensions is not needed, you can write the `when` method in the sealed class

- You can use the switch pattern matching instead of `if (this is xxxx)` which will be exaustive (this is a sealed class so there's no more case: else is useless) in the `when` method

- Prefer "standard" method's name for `when` like `fold` or `match`

But it is a good try 👍 even if I think that using a functional programming library like fpdart is much better because of its composition capabilities 😉

**Comment by rishad13** [comment]
Thank you so much for the feedback—it’s really helpful! 😊

**Comment by rishad13** [comment]
I’ve made some changes based on your suggestions. You can check the updated implementation on the scaled_class_type branch. Let me know what you think! 😊

**Comment by eric-taix** [comment]
LGTM👍
